#!/usr/bin/env bash
# =============================================================================
#  SignFlow CMS — hardware video encoding
#
#  Usage:  sudo bash setup-gpu.sh            enable (detect, wire, verify)
#          sudo bash setup-gpu.sh --off      back to CPU encoding
#          sudo bash setup-gpu.sh --status   what the worker can really use
#
#  Transcoding is by far the heaviest task this server performs. SignFlow already
#  picks the best encoder on its own — it TESTS nvenc, qsv and vaapi in turn and
#  falls back to libx264 — so the only thing missing is ACCESS to the hardware
#  from inside the container. That is what this script arranges.
#
#  ⚠️ IT NEVER INSTALLS A GPU DRIVER. Installing a proprietary driver on someone
#  else's server can break their display stack and require a reboot to recover.
#  We use the driver that is already there, or we do without. If you have just
#  fitted a card, install your vendor's driver first, then run this.
#
#  Why this exists as its own script: the same wiring used to live only inside
#  install-ubuntu.sh, so it ran ONLY at install time. A customer who added a card
#  six months later had no supported path — neither to enable it, nor to go back.
#  install-ubuntu.sh now sources this file, so there is a single definition:
#  two copies would drift, and the drift would be silent.
# =============================================================================
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/signflow}"
SERVICE_USER="${SERVICE_USER:-${SUDO_USER:-root}}"
OVERRIDE="docker-compose.override.yml"
# Marks the file as ours, so --off never deletes an override written by the
# operator. The historical header is recognised too: installs made before this
# script existed carry it.
GPU_MARK="SignFlow GPU wiring"
GPU_MARK_LEGACY="Generated by install-ubuntu.sh"

# When sourced by install-ubuntu.sh these already exist — do not clobber them.
if ! declare -F ok >/dev/null 2>&1; then
    _R='\033[0;31m'; _G='\033[0;32m'; _Y='\033[1;33m'; _C='\033[0;36m'; _N='\033[0m'
    step()  { echo -e "\n${_C}[$(date +%H:%M:%S)] $*${_N}"; }
    ok()    { echo -e "${_G}    OK  $*${_N}"; }
    warn()  { echo -e "${_Y}    !!  $*${_N}"; }
    fail()  { echo -e "${_R}    ERR $*${_N}"; exit 1; }
    info()  { echo -e "    ..  $*"; }
fi

# ── Detection ────────────────────────────────────────────────────────────────
# Sets GPU_MODE to nvidia | dri | none, installing the container toolkit and
# configuring the Docker runtime when that is what NVIDIA needs.
#
# Order matters: a machine can expose /dev/dri (Intel iGPU) *and* hold an NVIDIA
# card. NVIDIA is checked first because it is the faster encoder.
gpu_detect() {
    GPU_MODE="none"

    # The card being present is NOT enough: without a working driver the toolkit
    # has nothing to talk to. `nvidia-smi` answering is the only reliable proof
    # that the driver is loaded and healthy.
    if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
        GPU_MODE="nvidia"
        info "NVIDIA GPU detected: $(nvidia-smi -L 2>/dev/null | head -1)"

        if ! command -v nvidia-ctk >/dev/null 2>&1; then
            info "Installing nvidia-container-toolkit (driver untouched)"
            curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
                | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg 2>/dev/null \
                || { warn "Could not fetch the NVIDIA key — falling back to CPU encoding"; GPU_MODE="none"; }
            if [[ "$GPU_MODE" == "nvidia" ]]; then
                curl -fsSL https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
                    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
                    > /etc/apt/sources.list.d/nvidia-container-toolkit.list
                apt-get update -qq
                apt-get install -y -qq nvidia-container-toolkit >/dev/null \
                    || { warn "nvidia-container-toolkit failed to install — falling back to CPU"; GPU_MODE="none"; }
            fi
        fi

        if [[ "$GPU_MODE" == "nvidia" ]]; then
            # ⚠️ `nvidia-ctk runtime configure` rewrites /etc/docker/daemon.json, and
            # the change only takes effect once the Docker DAEMON restarts. At install
            # time no container exists yet; run afterwards, this briefly restarts the
            # running ones — announced by gpu_enable() before we get here.
            nvidia-ctk runtime configure --runtime=docker >/dev/null 2>&1 \
                || { warn "nvidia-ctk configure failed — falling back to CPU"; GPU_MODE="none"; }
            if [[ "$GPU_MODE" == "nvidia" ]]; then
                systemctl restart docker
                for _ in $(seq 1 15); do docker info >/dev/null 2>&1 && break; sleep 1; done
                docker info >/dev/null 2>&1 || fail "Docker did not come back after restart."
                ok "NVIDIA runtime configured (Docker restarted)"
            fi
        fi
    fi

    # Intel / AMD — VAAPI and QuickSync go through the DRM render node. Nothing to
    # install: the kernel driver ships with Ubuntu and the image already carries the
    # userspace bits. Passing the device through costs nothing when the encoder
    # turns out to be unusable, because SignFlow falls back on its own.
    if [[ "$GPU_MODE" == "none" ]] && compgen -G "/dev/dri/renderD*" >/dev/null 2>&1; then
        GPU_MODE="dri"
        info "DRM render node detected: $(ls /dev/dri/renderD* | tr '\n' ' ')"
    fi

    case "$GPU_MODE" in
        nvidia) ok "Hardware encoding: NVIDIA (NVENC)" ;;
        dri)    ok "Hardware encoding: Intel/AMD (VAAPI or QuickSync)" ;;
        none)   info "No usable GPU found — encoding on CPU (libx264). Nothing is broken." ;;
    esac
}

# ── Wiring ───────────────────────────────────────────────────────────────────
# Writes docker-compose.override.yml, which Compose loads automatically: a plain
# `docker compose up -d` picks it up with no extra flag, including from the
# systemd unit. Only celery-media needs it — it is the ONLY service that
# transcodes (verified: app/core/encoders is imported by media_worker alone).
gpu_write_override() {
    [[ "${GPU_MODE:-none}" == "none" ]] && return 0
    if [[ -f "$OVERRIDE" ]] \
       && ! grep -q "$GPU_MARK" "$OVERRIDE" 2>/dev/null \
       && ! grep -q "$GPU_MARK_LEGACY" "$OVERRIDE" 2>/dev/null; then
        warn "$OVERRIDE exists and was not written by us — left untouched."
        warn "GPU access NOT configured; merge the block by hand if you want it."
        return 0
    fi

    if [[ "$GPU_MODE" == "nvidia" ]]; then
        cat > "$OVERRIDE" << 'EOF'
# SignFlow GPU wiring — NVIDIA hardware encoding.
# Written by setup-gpu.sh. Run `sudo bash setup-gpu.sh --off` to go back to CPU.
services:
  celery-media:
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      # ⚠️ "video" is what exposes NVENC. With the default capabilities the GPU
      # appears inside the container but the encoder is absent, and ffmpeg fails
      # with a misleading "unknown encoder h264_nvenc".
      NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
EOF
        ok "NVIDIA access written to $OVERRIDE"
    else
        cat > "$OVERRIDE" << 'EOF'
# SignFlow GPU wiring — Intel/AMD hardware encoding (VAAPI/QuickSync).
# Written by setup-gpu.sh. Run `sudo bash setup-gpu.sh --off` to go back to CPU.
services:
  celery-media:
    devices:
      - /dev/dri:/dev/dri
EOF
        ok "DRM render node access written to $OVERRIDE"
    fi
    chown "$SERVICE_USER:$SERVICE_USER" "$OVERRIDE" 2>/dev/null || true
}

# ── Verification ─────────────────────────────────────────────────────────────
# Passing the device through is NOT proof that it works: the driver may be too
# old, the capability missing, the node unreadable. SignFlow then falls back to
# libx264 SILENTLY — correct behaviour, but the operator would believe the server
# encodes on GPU when it does not. So we ask the worker itself, inside its own
# container, which encoders it can really use.
#
# Returns 0 when at least one hardware encoder is usable.
gpu_verify() {
    local hw
    hw=$(docker compose exec -T celery-media python3 -c \
        "from app.core import encoders; print(','.join(encoders.detect_hw_encoders()))" \
        2>/dev/null | tr -d '\r')
    if [[ -n "$hw" ]]; then
        ok "Hardware encoding active: ${hw}"
        return 0
    fi
    warn "No hardware encoder is usable from inside the container."
    warn "Transcoding will run on CPU — correct, just slower."
    warn "Inspect with: docker compose exec celery-media ffmpeg -encoders | grep -E 'nvenc|vaapi|qsv'"
    return 1
}

# ── Commands (standalone use) ────────────────────────────────────────────────
gpu_enable() {
    step "Hardware video encoding — enabling"
    [[ -d "$INSTALL_DIR" ]] || fail "$INSTALL_DIR not found — is SignFlow installed here?"
    cd "$INSTALL_DIR"

    if ! command -v nvidia-smi >/dev/null 2>&1 && ! compgen -G "/dev/dri/renderD*" >/dev/null 2>&1; then
        warn "No GPU driver answers on this machine."
        warn "This script never installs one: fit the card, install your vendor's"
        warn "driver until \`nvidia-smi\` answers, then run this script again."
        exit 1
    fi
    warn "Enabling NVIDIA support restarts the Docker daemon: running containers"
    warn "will bounce for a few seconds. Playback on the screens is not affected"
    warn "(players keep their content and reconnect on their own)."

    gpu_detect
    if [[ "$GPU_MODE" == "none" ]]; then
        fail "No usable GPU — nothing was changed."
    fi
    gpu_write_override
    info "Applying to celery-media ..."
    docker compose up -d celery-media >/dev/null 2>&1 || fail "Could not restart celery-media."
    sleep 3
    if gpu_verify; then
        ok "Done. New uploads will transcode on the GPU."
    else
        warn "The wiring is in place but the encoder is not usable — see above."
        warn "Nothing is broken: transcoding continues on CPU."
        exit 1
    fi
}

gpu_disable() {
    step "Hardware video encoding — disabling"
    [[ -d "$INSTALL_DIR" ]] || fail "$INSTALL_DIR not found — is SignFlow installed here?"
    cd "$INSTALL_DIR"
    if [[ ! -f "$OVERRIDE" ]]; then
        info "No $OVERRIDE — already on CPU encoding. Nothing to do."
        exit 0
    fi
    if ! grep -q "$GPU_MARK" "$OVERRIDE" 2>/dev/null \
       && ! grep -q "$GPU_MARK_LEGACY" "$OVERRIDE" 2>/dev/null; then
        fail "$OVERRIDE was not written by us — refusing to delete it. Edit it by hand."
    fi
    mv "$OVERRIDE" "${OVERRIDE}.disabled-$(date +%Y%m%d-%H%M%S)"
    ok "Override moved aside (kept as .disabled-* in case you want it back)."
    info "Applying to celery-media ..."
    docker compose up -d celery-media >/dev/null 2>&1 || fail "Could not restart celery-media."
    sleep 3
    # Here an EMPTY answer is the expected outcome, so gpu_verify's non-zero exit
    # is success — hence the explicit handling rather than `gpu_verify || fail`.
    if gpu_verify >/dev/null 2>&1; then
        warn "A hardware encoder is STILL visible — check $INSTALL_DIR for another override."
        exit 1
    fi
    ok "Back to CPU encoding (libx264)."
}

gpu_status() {
    [[ -d "$INSTALL_DIR" ]] || fail "$INSTALL_DIR not found — is SignFlow installed here?"
    cd "$INSTALL_DIR"
    echo ""
    if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
        info "Driver on the host : $(nvidia-smi -L 2>/dev/null | head -1)"
    elif compgen -G "/dev/dri/renderD*" >/dev/null 2>&1; then
        info "Driver on the host : DRM render node ($(ls /dev/dri/renderD* | tr '\n' ' '))"
    else
        info "Driver on the host : none answering"
    fi
    # The only answer that matters is what the worker can really use — but the
    # tone depends on intent. No wiring means CPU encoding ON PURPOSE, which is a
    # perfectly good state: saying it with a warning would train the operator to
    # ignore warnings. The alarm belongs to the case where the wiring IS there
    # and the encoder still is not usable — that one is a real problem.
    if [[ -f "$OVERRIDE" ]]; then
        info "Wiring             : $OVERRIDE present"
        gpu_verify || true
    else
        info "Wiring             : none — encoding on CPU (libx264), as configured"
        if gpu_verify >/dev/null 2>&1; then
            warn "A hardware encoder is visible even without wiring — unexpected;"
            warn "look for another override or a runtime default in /etc/docker/daemon.json."
        else
            info "Run 'sudo bash setup-gpu.sh' to use a GPU, if this machine has one."
        fi
    fi
    echo ""
}

# Sourced as a library by install-ubuntu.sh: define the functions and stop.
[[ "${1:-}" == "--lib" ]] && return 0 2>/dev/null

case "${1:-}" in
    ""|--on|on)          gpu_enable ;;
    --off|off)           gpu_disable ;;
    --status|status)     gpu_status ;;
    -h|--help)
        sed -n '2,22p' "$0" | sed 's/^#\s\?//'
        ;;
    *) echo "usage: sudo bash setup-gpu.sh [--on|--off|--status]"; exit 1 ;;
esac
